//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProduct()
        {
            this.tblDeliveryNoteItems = new HashSet<tblDeliveryNoteItem>();
            this.tblInventoryItems = new HashSet<tblInventoryItem>();
            this.tblInvoiceItems = new HashSet<tblInvoiceItem>();
            this.tblQuotationItems = new HashSet<tblQuotationItem>();
        }
    
        public int ProductID { get; set; }
        public Nullable<int> ProductCategoryID { get; set; }
        public Nullable<int> ProductSubCategoryID { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public string Make { get; set; }
        public Nullable<int> TaxID { get; set; }
        public Nullable<int> SizeID { get; set; }
        public Nullable<decimal> RatePerUnit { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string Remark { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public Nullable<decimal> CGST { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDeliveryNoteItem> tblDeliveryNoteItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblInventoryItem> tblInventoryItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblInvoiceItem> tblInvoiceItems { get; set; }
        public virtual tblProductCategory tblProductCategory { get; set; }
        public virtual tblProductSubCategory tblProductSubCategory { get; set; }
        public virtual tblSize tblSize { get; set; }
        public virtual tblTax tblTax { get; set; }
        public virtual tblUnit tblUnit { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQuotationItem> tblQuotationItems { get; set; }
    }
}
